name-template: 'v$NEXT_PATCH_VERSION 🌈'
tag-template: 'v$NEXT_PATCH_VERSION'
branches:
  - refs/head/1.0.z
  - 1.0.z
categories:
  - title: '🚀 New features and improvements'
    labels:
      - 'new'
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📖 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- #$NUMBER: $TITLE (@$AUTHOR)'
template: |
  ## Product Changes
  $CHANGES
  All contributors: $CONTRIBUTORS
