name: "Daily Build"
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Draft product release
        uses: release-drafter/release-drafter@v5.17.6
        with:
          config-name: product-release-drafter.yml
          name: Product Pre-release
          commitish: main
          tag: 1.0.1
          publish: true
          prerelease: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
